### ISSUE TITLE
[BugFix] Unimplemented function may cause render fail, please delete

### ISSUE THREAD

**Issue by bzdfzfer** [humansensinglab/taming-3dgs#10]
https://github.com/humansensinglab/taming-3dgs/blob/bc5e57602ebe54002e16cd0e573885ca4e102036/submodules/diff-gaussian-rasterization/rasterize_points.h#L121-L130

**Comment by PenghaoYin** [comment]
Maybe you need to renew other related codes in diff-gaussian-rasterization at the same time, or it will cause the error "‘fusedssim_backward’ was not declared in this scope" when installing the package diff-gaussian-rasterization. Below is the detail of this error.
`      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      ext.cpp: In function ‘void pybind11_init__C(pybind11::module_&)’:
      ext.cpp:21:32: error: ‘fusedssim_backward’ was not declared in this scope
         21 |   m.def("fusedssim_backward", &fusedssim_backward);
            |                                ^~~~~~~~~~~~~~~~~~
      error: command '/usr/bin/gcc-9' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> diff_gaussian_rasterization

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`
I would greatly appreciate it if you could take some time to review this problem, as it would be incredibly helpful for new learners like me. Thank you!

**Comment by PenghaoYin** [comment]
> Maybe you need to renew other related codes in diff-gaussian-rasterization at the same time, or it will cause the error "‘fusedssim_backward’ was not declared in this scope" when installing the package diff-gaussian-rasterization. Below is the detail of this error. ` cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ ext.cpp: In function ‘void pybind11_init__C(pybind11::module_&)’: ext.cpp:21:32: error: ‘fusedssim_backward’ was not declared in this scope 21 | m.def("fusedssim_backward", &fusedssim_backward); | ^~~~~~~~~~~~~~~~~~ error: command '/usr/bin/gcc-9' failed with exit code 1 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure
> 
> × Encountered error while trying to install package. ╰─> diff_gaussian_rasterization
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.` I would greatly appreciate it if you could take some time to review this problem, as it would be incredibly helpful for new learners like me. Thank you!

I have finally solved this problem by deleting the code "m.def("fusedssim_backward", &fusedssim_backward);" in ext.cpp. Sorry for disturbing authors of this code!
