### ISSUE TITLE
diff-gaussian-rasterization

### ISSUE THREAD

**Issue by norris-H** [humansensinglab/taming-3dgs#11]
Hi, thanks for your great work !

I installed your module 'submodules/diff-gaussian-rasterization/', and then ran the command 'python train.py -s /root/autodl-tmp/taming-3dgs/data/ggbond/ --eval --densification_interval 100 --mode "final_count" --budget 5987095 --optimizer_type default --test_iterations 30000 --sh_lower', but an error occurred.

Traceback (most recent call last):
  File "/root/autodl-tmp/taming-3dgs/train.py", line 19, in <module>
    from gaussian_renderer import render, network_gui_ws
  File "/root/autodl-tmp/taming-3dgs/gaussian_renderer/__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "/root/miniconda3/envs/3dgs/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: /root/miniconda3/envs/3dgs/lib/python3.10/site-packages/diff_gaussian_rasterization/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _Z18fusedssim_backwardffRN2at6TensorES1_S1_S1_S1_S1_

Do you know what this problem is?

**Comment by saswat0** [comment]
@norris-H These errors might turn up with some version differences in python. Could you try creating a conda environment using our yml file?

**Comment by PenghaoYin** [comment]
I tried to create a conda environment with environment.yml, but still faced that problem. Is there any other solution?

**Comment by mappro6** [comment]
I faced the same problem, although I tried to create a conda environment with environment.yml. This seems to be caused by the new commits, when I switch to an older version of diff-gaussian-rasterization it can be installed successfully. @saswat0

**Comment by KL-2** [comment]
> I tried to create a conda environment with environment.yml, but still faced that problem. Is there any other solution?

try this:https://github.com/humansensinglab/taming-3dgs/issues/10#issuecomment-2531562512
I met the same problem.I deleted m.def("fusedssim_backward", &fusedssim_backward); I can sucessfully install diff_gaussian_rasterization and render now.

**Comment by PenghaoYin** [comment]
> > I tried to create a conda environment with environment.yml, but still faced that problem. Is there any other solution?
> 
> try this:[#10 (comment)](https://github.com/humansensinglab/taming-3dgs/issues/10#issuecomment-2531562512) I met the same problem.I deleted m.def("fusedssim_backward", &fusedssim_backward); I can sucessfully install diff_gaussian_rasterization and render now.

Haha, this comment is raised by myself, but it doesn't work when I try to run the train.py file. I finally solved the problem by downlading the previous version of this repository.
