### ISSUE TITLE
clone_budget and split_budget negative leads to runtime error

### ISSUE THREAD

**Issue by tsepten** [humansensinglab/taming-3dgs#12]
In gaussian_model.py's densify_with_score(), I've run into run-time errors with clone_budget and split_budget <= 0 leading to torch.multinomial sampling runtime error (since num_samples needs to be > 0)

The calculation for clone_budget and split_budget should always be >= 0 right?

**Comment by saswat0** [comment]
@tsepten Could you please share the command to reproduce this?

**Comment by tsepten** [comment]
It was with default budget (0.2, multiplier). The math does (budget - curr_points) and curr points exceeded budget on first iteration of densification (500th training iteration). I'll try to reproduce it tomorrow

**Comment by saswat0** [comment]
A budget of 0.2 would mean you want to end up with fewer gaussians than you started with. Our method cannot handle such cases. The budget should be > 1

**Comment by tsepten** [comment]
Thats what i thought, but 0.2 is default budget value. Please change that
