### ISSUE TITLE
Installation and testing instructions 

### ISSUE THREAD

**Issue by JohannesKrueger** [humansensinglab/taming-3dgs#5]
Hello, thank you for developing the code. Are there instructions for installing and testing the algorithm?

**Comment by rahul-goel** [comment]
Hi! As mentioned in the README file, you can refer to the original Inria repository for the instructions: https://github.com/graphdeco-inria/gaussian-splatting.

In case you want to use the sparse adam optimizer, please pass the argument `--optimizer_type sparse_adam`.
