### ISSUE TITLE
Opacity activation function and separating SH from DC

### ISSUE THREAD

**Issue by anton-brandl** [humansensinglab/taming-3dgs#8]
Thanks a lot for publishing the code alongside the paper!

When looking at the code, I was a bit surprised that the activation function for the opacity is still the sigmoid function although the paper describes the use of the `abs` activation function in Section 3.4.

Similarly, I see the appeal for optimizing all SH bands except the first to a batched update schedule, but I can't find that in the code either.

Is there a reason you excluded this or am I just being blind?
Thanks a lot in advance!

**Comment by rahul-goel** [comment]
Hi.

As mentioned in the README, this is a partial code release which provides a more optimized training process to act as a drop-in replacement for the existing 3DGS code.

We're working on the full code and it will be released very soon.

Rahul
