### ISSUE TITLE
Error in user-defined budget function

### ISSUE THREAD

**Issue by KeKsBoTer** [humansensinglab/taming-3dgs#9]
Hello, 

I have a question regarding the user-defined budget function:

$$A(x) = \frac{B-S-2N}{N^2} x^2 + 2x +B$$

Could you tell me how you derived this formula? 
Plotting the function for $B=10^6, N=10,S=10^4$ gives the following curve:
![image](https://github.com/user-attachments/assets/1f22912e-c990-4926-948c-d126bbb0787c)

This is not what the curve in the paper (Fig. 2b) looks like. Also $A(0) = B$ which is unexpected, given that B is the final number of Gaussians.

Best
Simon

**Comment by saswat0** [comment]
@KeKsBoTer Thanks for pointing this issue. The budget function is defined by the following equation
![image](https://github.com/user-attachments/assets/88531a2f-dbf3-4e09-919b-29a170d03198)

We'll take necessary steps to address this in our paper
